---
name: ci

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rake

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - uses: ruby/setup-ruby@v1
      - run: gem install rubocop
      - run: rubocop